### ISSUE TITLE
Error in split.anno(anno[[1]]) : could not find function "split.anno"

### ISSUE THREAD

**Issue by GMFranceschini** [schmic05/ISH_package#6]
Hello,
I think there might be an error in the mentioned call within the `calculate_pdr()` function. 
It should be `anno.split()` instead, I guess. The error is within the conditional statement `if (length(anno) >= 22){...}`. 
Best

**Comment by schmic05** [comment]
Thanks for reporting this. It was, indeed, a bug that has been fixed with commit 16dcadb.
