### ISSUE TITLE
calculate.qfdrp(..., use.sex.chromosomes=T ) not working

### ISSUE THREAD

**Issue by rnbatra** [schmic05/ISH_package#7]
chr1,.., chr22 seems to work fine. But chrX and chrY are not working

calculate.qfdrp(..., use.sex.chromosomes=T ) gives the following error. 

Error in { : 
  task 1 failed - "supplied 'seqlevels' cannot contain NAs or empty strings ("")"

**Comment by schmic05** [comment]
Hi @rnbatra 

Thanks for pointing that out. Can you somehow share some data to reproduce the error such that I can fix it?

Thanks,

Michael

**Comment by rnbatra** [comment]
Hey, 
Sure I can send 2 small examples (for chr1 and chrX) of GRanges over email. Would you also need a bam file?

**Comment by schmic05** [comment]
That would be great, since I checked it with my examples yesterday and it worked fine. So I guess it is something dataset-specific.
